### PR TITLE
remove SinatraServiceController#logged_in?

### PR DESCRIPTION
**Pull request by mikesea**
This should probably just be left to the client applications to implement themselves.

### CODE REVIEW

**Comment by kamui** [comment]
I believe the sinatra framework extensions in there are only used by the testing harness in the library. Last time I checked, I don't think wd-sinatra made use of any of that.

**Comment by mikesea** [comment]
@kamui well, then I'll leave it up to you whether to merge this or not. :) At present, it's an untested method that is not used by the testing harness. I'd vote to just remove it, or move the framework extensions into the `spec` library to better highlight that they're only used by the tests.

**Comment by kamui** [comment]
I think most of those specs revolve around `controller_dispatch` which appears to be deprecated. So it might even make sense to remove those specs and the framework_ext code.

**Comment by mattetti** [comment]
Agreed

**Comment by mikesea** [comment]
I'll send a PR for that then.

**Pull request closed without merging**
