### PR TITLE
Remove controller dispatch and related dependencies

### PR DESCRIPTION
**Pull request by mikesea**
Okay, let's try this again. Since controller dispatch has been deprecated for some time now, I decided to remove that and all of its related dependencies (including Sinatra!). I think this simplifies things by an order of magnitude.

~~Because the framework extensions were requiring `params_verification` I moved that into `lib/weasel_diesel` or else it will only be available as an optional module. Let me know if you disagree with this change and I can modify.~~

### CODE REVIEW

**Comment by kamui** [comment]
Thanks for this PR @mikesea.

I'm not sure if `params_verification` should be required from weasel_diesel. It's more of a utility module there for generator implementations to use and weasel_diesel doesn't really use it internally for documentation generation. wd_sinatra requires it explicitly, but if you're using weasel_diesel just for the documentation aspect, you really don't need `params_verification` to be pulled in.

**Comment by mikesea** [comment]
After more thinking, moving around `params_verification` is outside the scope of this PR. Considering that and @kamui's comments above, I'm removing that particular commit.

**Comment by kamui** [comment]
:+1:

**Comment by kamui** [comment]
I'm not 100% sure, but I think :controller_name, :controller, and :action might also have been specific to the controller_dispatch feature.

**Comment by mattetti** [comment]
correct

**Pull request merged**
